### ISSUE TITLE
Logo will not generate business £300

### ISSUE THREAD

**Issue by samuel-bh** [Armodia-Systems/Branding#1]
The problem with this particular logo is that it does not have the ability to generate Armodia £300. I can forsee many possible problems with this, including the Managing Director needing to resign to focus on education after learning that this will not generate £300.

**Comment by ninjaninja140** [comment]
Time for some fun facts with Dylan!

In max's "Legal" agreement, he stated that the Armodia logo is not allowed to be changed!

Thanks for coming to my ted talk inneh

**Comment by samuel-bh** [comment]
This is disgraceful and will not be tolerated. I am contacting the Crown Courts as we speak. Good day.
